<?php
/** @var Magento\Backend\Block\Template $block */

/** @var Bodak\CheckoutCustomForm\Model\Data\CustomFields $customFields */
$customFields = $block->getOrderCustomFields();
?>
<?php if($customFields): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Other information') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="order-information">
              <div class="box">
                    <p class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Electronic billing code(SDI): ') ?>
                    
                    <strong><?php echo $this->escapeHtml($customFields->getCheckoutGoodsMark()); ?></strong>
                                    
                    </span></p>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>